-- The demo seed in 004 inserted auth.identities rows with
--   provider     = 'email'
--   provider_id  = <user_id::text>      <-- WRONG for current GoTrue
--
-- Modern Supabase Auth (gotrue >= ~2.155, mid-2024) expects the email
-- provider's provider_id to be the email address. Sign-in for those
-- seeded users surfaces as a generic "Database error querying schema".
--
-- Idempotent: the WHERE clause skips rows already correct.

update auth.identities i
   set provider_id = u.email
  from auth.users u
 where i.user_id = u.id
   and i.provider = 'email'
   and i.provider_id <> u.email;

-- Reset the password hashes to known-good bcrypt (cost 10) for the
-- demo seed accounts, in case gotrue is rejecting the cost-6 hashes
-- generated by gen_salt('bf') without an explicit cost.
update auth.users
   set encrypted_password = crypt('apto-demo-2025', gen_salt('bf', 10))
 where email like 'demo+cs-%@apto.test';

-- Make sure these flags are populated (the seed predates them on some
-- Supabase versions; defaults usually fill in, but be explicit).
update auth.users
   set is_sso_user   = coalesce(is_sso_user,   false),
       is_anonymous  = coalesce(is_anonymous,  false),
       email_confirmed_at = coalesce(email_confirmed_at, now())
 where email like 'demo+cs-%@apto.test';
